;/*FB_PKG_DELIM*/

__d("CometFeedStoryDropdownMenuLoggerContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext({nodeID:null});l.default=u}),98);
__d("FDSChevronLeftFilled12Icon",["cr:14702"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14702")}),98);
__d("FDSChevronRightFilled12Icon",["cr:13981"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13981")}),98);
__d("FDSEyeCrossFilled20Icon",["cr:14895"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14895")}),98);
__d("FDSEyeCrossFilled24Icon",["cr:13838"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13838")}),98);
__d("FDSResizeDownFilled20Icon",["cr:14080"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14080")}),98);
__d("XCometPageVanityNoMediasetPhotoControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/{vanity}/photos/{?set}/{fbid}/",Object.freeze({}),void 0),s=e;l.default=s}),98);
__d("XCometPageVanityPhotoControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/{vanity}/photos/{set}/{fbid}/",Object.freeze({}),void 0),s=e;l.default=s}),98);
__d("XCometPhotoControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/photo/",Object.freeze({vrnav:!1}),void 0),s=e;l.default=s}),98);
__d("addToSet",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){if(e.has(t))return e;var n=new Set(e);return n.add(t),n}i.default=e}),66);
__d("getCometMediaURL_media.graphql",[],(function(t,n,r,o,a,i){"use strict";var e={kind:"InlineDataFragment",name:"getCometMediaURL_media"};a.exports=e}),null);
__d("getCometMediaURL",["CometRelay","XCometPageVanityNoMediasetPhotoControllerRouteBuilder","XCometPageVanityPhotoControllerRouteBuilder","XCometPhotoControllerRouteBuilder","XCometVideoControllerRouteBuilder","getCometMediaURL_media.graphql","isStringNullOrEmpty"],(function(t,n,r,o,a,i,l){"use strict";var e;function s(t,a){var i,l,s,u,c=o("CometRelay").readInlineData(e!==void 0?e:e=n("getCometMediaURL_media.graphql"),t),d=c==null?void 0:c.id,m=(c==null?void 0:c.is_playable)===!0,p=(i=c==null||(l=c.owner)==null?void 0:l.uri_token)!=null?i:c==null||(s=c.owner)==null?void 0:s.id,_=(c==null||(u=c.owner)==null?void 0:u.__typename)==="Page";return d==null?null:m?p==null?null:r("XCometVideoControllerRouteBuilder").buildURL({page_token:p,set:a,story_token:d}):_&&p!=null?r("isStringNullOrEmpty")(a)?r("XCometPageVanityNoMediasetPhotoControllerRouteBuilder").buildURL({fbid:d,vanity:p}):r("XCometPageVanityPhotoControllerRouteBuilder").buildURL({fbid:d,set:a,vanity:p}):r("XCometPhotoControllerRouteBuilder").buildURL({fbid:d,set:a})}l.default=s}),98);
__d("removeFromSet",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){if(!e.has(t))return e;var n=new Set(e);return n.delete(t),n}i.default=e}),66);
__d("useCometMediaURL_media.graphql",[],(function(t,n,r,o,a,i){"use strict";var e=(function(){var e={alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},t=[e,{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"owner",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null},e,{kind:"InlineFragment",selections:[{alias:null,args:null,kind:"ScalarField",name:"uri_token",storageKey:null}],type:"Page",abstractKey:null}],storageKey:null}];return{argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useCometMediaURL_media",selections:[{kind:"InlineDataFragmentSpread",name:"getCometMediaURL_media",selections:[{alias:null,args:null,kind:"ScalarField",name:"is_playable",storageKey:null},{kind:"InlineFragment",selections:t,type:"Photo",abstractKey:null},{kind:"InlineFragment",selections:t,type:"Video",abstractKey:null}],args:null,argumentDefinitions:[]}],type:"Media",abstractKey:"__isMedia"}})();a.exports=e}),null);
__d("useCometMediaURL",["CometRelay","getCometMediaURL","react-compiler-runtime","useCometMediaURL_media.graphql"],(function(t,n,r,o,a,i,l){"use strict";var e;function s(t,a){var i=o("react-compiler-runtime").c(3),l=o("CometRelay").useFragment(e!==void 0?e:e=n("useCometMediaURL_media.graphql"),t),s;return i[0]!==l||i[1]!==a?(s=r("getCometMediaURL")(l,a),i[0]=l,i[1]=a,i[2]=s):s=i[2],s}l.default=s}),98);