;/*FB_PKG_DELIM*/

__d("CometEventPermalinkTab",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum")({ABOUT:"about",DISCUSSION:"discussion",BRACKETS:"brackets",BROADCASTS:"broadcasts",PARTICIPANTS:"participants",STANDINGS:"standings",VIDEOS:"videos",PAID_ACCESS:"paid_access"}),l=e;i.default=l}),66);
__d("EventCometActionContextDefault",[],(function(t,n,r,o,a,i){"use strict";var e={event_action_history:[]};i.default=e}),66);
__d("EventCometActionContext",["EventCometActionContextDefault","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext(r("EventCometActionContextDefault"));l.default=u}),98);
__d("EventCometActionLoggerUtils",["CometRouteURL"],(function(t,n,r,o,a,i,l){"use strict";var e={mechanism:"unknown",surface:"unknown"},s=3;function u(e,t){var n=[].concat(e.event_action_history||[]);n.length>=s&&(n=n.slice(n.length-s+1));var r=c(e);return n.push({event_tracking:r.event_tracking,extra_data:r.extra_data,mechanism:t.mechanism,surface:t.surface}),babelHelpers.extends({},e,{event_action_history:n})}function c(t){var n=t.event_action_history;return n==null||n[n.length-1]==null?e:n.length>=2?n[n.length-2]:n[n.length-1]}function d(){var e=o("CometRouteURL").useRouteURL(),t=/\/events\/\d+/;return t.test(e)?"permalink":e.includes("/events/calendar")?"bookmark_calendar":e.includes("/events")?"bookmark":e.includes("profile.php")?"timeline":"newsfeed"}l.createForNewSurface=u,l.getLastActionHistoryEntry=c,l.useExtractEventComposerSurface=d}),98);
__d("FDSStarFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("479327"),20),u=e;l.default=u}),98);
__d("WhatsappAdsUnsupportedCountryCodesSitevarConfig.experimental",["cr:13915"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13915")}),98);
__d("WhatsappAdsUnsupportedCountryCodesSitevarConfigJSModuleWrapper",["WhatsappAdsUnsupportedCountryCodesSitevarConfig"],(function(t,n,r,o,a,i,l){"use strict";l.default=r("WhatsappAdsUnsupportedCountryCodesSitevarConfig")}),98);
__d("XCometEventPermalinkControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/events/{event_id}/{?child_event_id}/",Object.freeze({active_tab:"about",show_created_event_toast:!1,hide_invite_flow_filter_groups:!1}),void 0),s=e;l.default=s}),98);