;/*FB_PKG_DELIM*/

__d("FBNucleusPinFilled20Icon.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsxs("svg",babelHelpers.extends({viewBox:"0 0 20 20",width:"1em",height:"1em",fill:"currentColor"},e,{children:[e.title!=null&&s.jsx("title",{children:e.title}),e.children!=null&&s.jsx("defs",{children:e.children}),s.jsx("path",{d:"M10 .5A7.5 7.5 0 0 0 2.5 8c0 2.257 1.214 4.62 2.545 6.558 1.35 1.963 2.91 3.616 3.773 4.475a1.667 1.667 0 0 0 2.363 0c.863-.86 2.423-2.512 3.773-4.475C16.285 12.62 17.5 10.258 17.5 8A7.5 7.5 0 0 0 10 .5zm0 4.25a3.25 3.25 0 1 1 0 6.5 3.25 3.25 0 0 1 0-6.5z"})]}))}u.displayName=u.name+" [from "+i.id+"]",u._size=20,u._isSVG=!0;var c=u;l.default=c}),98);
__d("FDSAppFacebookCircleFilled24Icon",["cr:13817"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13817")}),98);
__d("FDSAppFacebookCircleFilled24PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("869052"),24),u=e;l.default=u}),98);
__d("FDSAppMessengerFilled20Icon",["cr:14341"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14341")}),98);
__d("FDSCalendarFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("481118"),20),u=e;l.default=u}),98);
__d("FDSCamcorderFilled20Icon",["cr:14631"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14631")}),98);
__d("FDSLocationFilled20Icon",["cr:15234"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15234")}),98);
__d("FDSPencilFilled20Icon",["cr:14236"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14236")}),98);
__d("FDSPencilFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("477826"),20),u=e;l.default=u}),98);
__d("FDSPhoneFilled20Icon",["cr:15391"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15391")}),98);
__d("FDSPinFilled20Icon",["cr:13887"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13887")}),98);
__d("FDSPinFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("481942"),20),u=e;l.default=u}),98);
__d("FDSPostClockFilled20Icon",["cr:15477"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15477")}),98);
__d("useBaseDynamicEntryPointDialog",["CometDialogContext","CometRelay","CometSuspendedDialogImpl.react","clearTimeout","react","react-compiler-runtime","setTimeout","tracePolicyFromResource","useCometRelayEntrypointContextualEnvironmentProvider"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useCallback,d=u.useContext,m=u.useEffect,p=u.useRef;function _(e){var t=o("react-compiler-runtime").c(17),n=e.entryPoint,a=e.environmentProvider,i=e.onClose,l=e.otherProps,u=e.overrideRelayEnv,c=e.preloadedEntryPoint,d=e.preloadParams,_=o("CometRelay").useEntryPointLoader(a,n),f=_[0],g=_[1],h=_[2],y=f!=null?f:c,C=p(null),b,v;t[0]!==h||t[1]!==y.isDisposed||t[2]!==d||t[3]!==c||t[4]!==g||t[5]!==f?(b=function(){return C.current!=null&&(r("clearTimeout")(C.current),C.current=null),y.isDisposed&&g(d),(function(){C.current=r("setTimeout")(function(){f?h():c.dispose(),C.current=null},6e4)})},v=[h,y.isDisposed,c,d,g,f],t[0]=h,t[1]=y.isDisposed,t[2]=d,t[3]=c,t[4]=g,t[5]=f,t[6]=b,t[7]=v):(b=t[6],v=t[7]),m(b,v);var S;t[8]!==i||t[9]!==l?(S=babelHelpers.extends({},l,{onClose:i}),t[8]=i,t[9]=l,t[10]=S):S=t[10];var R=S,L;t[11]!==c||t[12]!==R?(L=s.jsx(o("CometRelay").EntryPointContainer,{entryPointReference:c,props:R}),t[11]=c,t[12]=R,t[13]=L):L=t[13];var E=L,k;return t[14]!==E||t[15]!==u?(k=u!=null?s.jsx(o("CometRelay").RelayEnvironmentProvider,{environment:u,children:E}):E,t[14]=E,t[15]=u,t[16]=k):k=t[16],k}function f(e,t,n,a){var i=o("react-compiler-runtime").c(7),l=r("useCometRelayEntrypointContextualEnvironmentProvider")(a),s=d(r("CometDialogContext")),u;return i[0]!==s||i[1]!==e||i[2]!==l||i[3]!==n||i[4]!==a||i[5]!==t?(u=function(u,c,d,m,p){var i=o("CometRelay").loadEntryPoint(l,e,u),f=function(){for(var e=arguments.length,t=new Array(e),n=0;n<e;n++)t[n]=arguments[n];var r=t;d&&d.apply(void 0,r),i.dispose()};s(r("CometSuspendedDialogImpl.react"),{dialog:_,dialogProps:{entryPoint:e,environmentProvider:l,otherProps:c,overrideRelayEnv:a,preloadedEntryPoint:i,preloadParams:u},fallback:n},{loadType:"entrypoint",preloadTrigger:t,tracePolicy:m!=null?m:r("tracePolicyFromResource")("comet.dialog",e.root)},f,{replaceCurrentDialog:p})},i[0]=s,i[1]=e,i[2]=l,i[3]=n,i[4]=a,i[5]=t,i[6]=u):u=i[6],u}l.default=f}),98);
__d("useCometDynamicEntryPointDialog",["FDSDialogLoadingState.react","react","useBaseDynamicEntryPointDialog"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=function(t){return s.jsx(r("FDSDialogLoadingState.react"),{onClose:t})};function c(e,t,n,o){return r("useBaseDynamicEntryPointDialog")(e,t,n!=null?n:u,o)}l.default=c}),98);